# Generated by Django 3.0.5 on 2020-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
