# Generated by Django 3.0.5 on 2020-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200804_0008'),
        ('pages', '0006_auto_20200804_0019'),
    ]

    operations = [
    ]
