# Generated by Django 3.0.5 on 2020-08-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_merge_20200804_1948'),
        ('pages', '0007_merge_20200804_0231'),
    ]

    operations = [
    ]
