# Generated by Django 3.0.3 on 2020-08-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_review_photo'),
        ('pages', '0009_auto_20200806_2051'),
    ]

    operations = [
    ]
