# Generated by Django 3.0.5 on 2020-08-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200806_2122'),
        ('pages', '0011_merge_20200807_1447'),
    ]

    operations = [
    ]
