# Generated by Django 3.0.5 on 2020-08-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_merge_20200807_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
