# Generated by Django 3.0.5 on 2020-08-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_review_photo'),
        ('pages', '0012_merge_20200807_1604'),
    ]

    operations = [
    ]
