# Generated by Django 3.0.5 on 2020-08-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0014_merge_20200813_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='rec_users',
            field=models.ManyToManyField(blank=True, related_name='rec_feeds', through='pages.ReviewRec', to=settings.AUTH_USER_MODEL),
        ),
    ]
