# Generated by Django 3.0.5 on 2020-08-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0015_auto_20200813_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ReviewComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='rec_users',
            field=models.ManyToManyField(blank=True, related_name='rec_comments', through='pages.CommentRec', to=settings.AUTH_USER_MODEL),
        ),
    ]
